# Generated by Django 5.0.6 on 2026-04-14 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_audience_award', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Award Category',
                'verbose_name_plural': 'Award Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AwardWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_special_mention', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text="e.g. 'Best Director: John Doe'")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='awards.awardcategory')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_winners', to='editions.edition')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_won', to='works.work')),
            ],
            options={
                'verbose_name': 'Award Winner',
                'verbose_name_plural': 'Award Winners',
                'ordering': ['category__order', 'category__name'],
            },
        ),
    ]
