// Static root redirect to /es — no JS required.
// On Netlify this is backed by the _redirects rule generated by next export.
export default function RootPage() {
  return (
    <html>
      <head>
        <meta httpEquiv="refresh" content="0;url=/es" />
      </head>
      <body />
    </html>
  );
}

