# Generated by Django 5.0.6 on 2026-04-14 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('original_title', models.CharField(blank=True, max_length=150)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('synopsis', models.TextField(blank=True)),
                ('year_produced', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='films/posters/')),
                ('section', models.CharField(blank=True, help_text='Festival section or category', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='editions.edition')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ['title'],
            },
        ),
    ]
