# Generated by Django 5.0.6 on 2026-04-17 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('masterclass', 'Masterclass'), ('panel', 'Panel'), ('exhibition', 'Exhibición'), ('opening', 'Apertura'), ('closing', 'Cierre'), ('awards', 'Entrega de Premios'), ('presentation', 'Presentación'), ('other', 'Otro')], default='other', max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_pt', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, upload_to='events/posters/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_events', to='editions.edition')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_events', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Special Event',
                'verbose_name_plural': 'Special Events',
                'ordering': ['date', 'time', 'order'],
            },
        ),
    ]
