# Generated by Django 5.0.6 on 2026-04-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_intro_es', models.TextField(blank=True, help_text='Hero / intro text shown on the homepage (Spanish)')),
                ('homepage_intro_en', models.TextField(blank=True, help_text='Hero intro text (English)')),
                ('homepage_intro_pt', models.TextField(blank=True, help_text='Hero intro text (Portuguese)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('letterboxd', 'Letterboxd'), ('other', 'Other')], max_length=30)),
                ('label', models.CharField(blank=True, help_text='Display label (optional override)', max_length=100)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'platform'],
            },
        ),
    ]
