# Generated by Django 5.0.6 on 2026-04-14 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.PositiveSmallIntegerField(help_text='Edition number (e.g., 16 for the 16th edition)')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('past', 'Past')], default='upcoming', max_length=20)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('poster', models.ImageField(blank=True, upload_to='editions/posters/')),
                ('key_visual', models.ImageField(blank=True, upload_to='editions/visuals/')),
                ('description_es', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_pt', models.TextField(blank=True)),
                ('rules_es', models.TextField(blank=True)),
                ('rules_en', models.TextField(blank=True)),
                ('rules_pt', models.TextField(blank=True)),
                ('submission_url', models.URLField(blank=True)),
                ('pdf_catalog', models.FileField(blank=True, upload_to='editions/catalogs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='EditionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='editions/gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='editions.edition')),
            ],
            options={
                'verbose_name': 'Edition Image',
                'verbose_name_plural': 'Edition Images',
                'ordering': ['order'],
            },
        ),
    ]
