# Generated by Django 5.0.6 on 2026-04-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='legacy_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
