# Generated by Django 5.0.6 on 2026-04-14 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('original_title', models.CharField(blank=True, max_length=300)),
                ('type', models.CharField(choices=[('short', 'Short Film'), ('medium', 'Medium-length'), ('feature', 'Feature Film')], max_length=20)),
                ('section', models.CharField(choices=[('competition_int', 'International Competition'), ('competition_nat', 'National Competition'), ('short_competition', 'Short Film Competition'), ('panorama', 'Panorama'), ('special', 'Special Screening'), ('retrospective', 'Retrospective'), ('tribute', 'Tribute')], default='competition_int', max_length=30)),
                ('participation_status', models.CharField(choices=[('selected', 'Official Selection'), ('world_premiere', 'World Premiere'), ('latam_premiere', 'Latin American Premiere'), ('regional_premiere', 'Regional Premiere'), ('special_screening', 'Special Screening')], default='selected', max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('production_year', models.PositiveSmallIntegerField()),
                ('runtime', models.PositiveSmallIntegerField(help_text='Runtime in minutes')),
                ('language', models.CharField(blank=True, max_length=100)),
                ('subtitles', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(max_length=300)),
                ('cast', models.TextField(blank=True, help_text='Cast list, comma-separated')),
                ('producers', models.CharField(blank=True, max_length=500)),
                ('synopsis_es', models.TextField(blank=True)),
                ('synopsis_en', models.TextField(blank=True)),
                ('synopsis_pt', models.TextField(blank=True)),
                ('still', models.ImageField(blank=True, upload_to='works/stills/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='editions.edition')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'ordering': ['section', 'title'],
            },
        ),
    ]
