# Generated by Django 5.0.6 on 2026-04-14 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
        ('venues', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True, help_text='Q&A, presentation, special notes, etc.')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='editions.edition')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings', to='venues.venue')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='works.work')),
            ],
            options={
                'verbose_name': 'Screening',
                'verbose_name_plural': 'Screenings',
                'ordering': ['date', 'time'],
            },
        ),
    ]
